version: '3.8'
services:
  ejecutorssh:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
      - ./app.py:/app/app.py
    environment:
      - FLASK_ENV=development
